# Generated by Django 6.0 on 2026-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainingday_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True),
        ),
    ]
