# Generated by Django 6.0 on 2026-01-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainingday_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayexercise',
            name='training_day',
        ),
        migrations.RemoveField(
            model_name='dayexercise',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dayexercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.DeleteModel(
            name='TrainingDay',
        ),
    ]
