# Generated by Django 6.0 on 2026-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dayexercise_training_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayexercise',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True),
        ),
    ]
